structure:
  readme: README.md
  summary: SUMMARY.md

redirects:
  'appudto/1hajimeni/dong-zuo-huan-jing': 'getting-started/operating-environment.md'
  'appudto/1hajimeni/nettowku': 'getting-started/supported-networks.md'
  'appudto/1hajimeni/roguin': 'getting-started/first-login.md'
  'appudto/2matome': 'setup/README.md'
  'appudto/2matome/ke': 'setup/admin/README.md'
  'appudto/2matome/ke/chmurru': 'setup/admin/organization-team-roles/README.md'
  'appudto/2matome/ke/chmurru/chmu': 'setup/admin/team/README.md'
  'appudto/2matome/ke/chmurru/chmu/chmuhenoadoresu': 'setup/admin/team/register-team-addresses.md'
  'appudto/2matome/ke/chmurru/chmu/chmuhenomenb': 'setup/admin/team/add-team-members.md'
  'appudto/2matome/ke/chmurru/chmu/chmumenbno': 'setup/admin/team/edit-delete-team-members.md'
  'appudto/2matome/ke/chmurru/rru': 'setup/admin/roles/README.md'
  'appudto/2matome/ke/chmurru/rru/chmurruno': 'setup/admin/roles/team-roles.md'
  'appudto/2matome/ke/chmurru/rru/rruno': 'setup/admin/roles/organization-roles.md'
  'appudto/2matome/ke/chmurru/zu-zhi': 'setup/admin/organization/README.md'
  'appudto/2matome/ke/chmurru/zu-zhi/chmuno': 'setup/admin/organization/create-team.md'
  'appudto/2matome/ke/chmurru/zu-zhi/henomenb': 'setup/admin/organization/add-organization-members.md'
  'appudto/2matome/ke/er-yao-su-ren-zheng-2fa': 'setup/admin/two-factor-authentication.md'
  'appudto/2matome/ke/wkufur': 'setup/admin/workflow/README.md'
  'appudto/2matome/ke/wkufur/purosesuni-wosuru': 'setup/admin/workflow/set-process-conditions.md'
  'appudto/2matome/ke/wkufur/wkufurnopurosesu': 'setup/admin/workflow/configure-workflow-process.md'
  'appudto/3.-shu-ming-jian-guan-li': 'key-management/README.md'
  'appudto/3.-shu-ming-jian-guan-li/aws-kms': 'key-management/aws-kms/README.md'
  'appudto/3.-shu-ming-jian-guan-li/aws-kms/adoresunon-walletheno': 'key-management/aws-kms/add-address-to-n-wallet.md'
  'appudto/3.-shu-ming-jian-guan-li/aws-kms/adoresuton-cloud-keyheno': 'key-management/aws-kms/register-address-name-in-n-cloud-key.md'
  'appudto/3.-shu-ming-jian-guan-li/aws-kms/aws-kmsno-macoske': 'key-management/aws-kms/create-aws-kms-private-key-macos.md'
  'appudto/3.-shu-ming-jian-guan-li/aws-kms/aws-kmsnowindowske': 'key-management/aws-kms/create-aws-kms-private-key-windows.md'
  'appudto/3.-shu-ming-jian-guan-li/aws-kms/iamporishnonowosuru': 'key-management/aws-kms/create-iam-policy-for-signing.md'
  'appudto/3.-shu-ming-jian-guan-li/aws-kms/iamyznonoyzwosuru': 'key-management/aws-kms/create-iam-user-for-signing.md'
  'appudto/3.-shu-ming-jian-guan-li/aws-kms/n-walletnoappudto': 'key-management/aws-kms/update-n-wallet.md'
  'appudto/3.-shu-ming-jian-guan-li/aws-kms/n-walletnoaws-kmsnoadoresu': 'key-management/aws-kms/register-aws-kms-address-in-n-wallet.md'
  'appudto/3.-shu-ming-jian-guan-li/aws-kms/n-walletnoinsutru': 'key-management/aws-kms/install-n-wallet.md'
  'appudto/3.-shu-ming-jian-guan-li/aws-kms/roguin': 'key-management/aws-kms/first-login.md'
  'appudto/3.-shu-ming-jian-guan-li/ledger': 'key-management/ledger/README.md'
  'appudto/3.-shu-ming-jian-guan-li/ledger/adoresunon-walletheno': 'key-management/ledger/add-address-to-n-wallet.md'
  'appudto/3.-shu-ming-jian-guan-li/ledger/adoresuton-cloud-keyheno': 'key-management/ledger/register-address-name-in-n-cloud-key.md'
  'appudto/3.-shu-ming-jian-guan-li/ledger/n-walletnoappudto': 'key-management/ledger/update-n-wallet.md'
  'appudto/3.-shu-ming-jian-guan-li/ledger/n-walletnoinsutru': 'key-management/ledger/install-n-wallet.md'
  'appudto/3.-shu-ming-jian-guan-li/ledger/n-walletnoledgernoadoresu': 'key-management/ledger/register-ledger-address-in-n-wallet.md'
  'appudto/3.-shu-ming-jian-guan-li/maruchishiguworetto': 'key-management/multisig-wallet/README.md'
  'appudto/3.-shu-ming-jian-guan-li/maruchishiguworetto/maruchishiguworettono': 'key-management/multisig-wallet/overview.md'
  'appudto/3.-shu-ming-jian-guan-li/maruchishiguworetto/maruchishiguworettono-1': 'key-management/multisig-wallet/initial-setup.md'
  'appudto/3.-shu-ming-jian-guan-li/maruchishiguworetto/nomaruchishiguworettoheadoresuwo': 'key-management/multisig-wallet/add-address-to-existing-multisig-wallet.md'
  'appudto/3.-shu-ming-jian-guan-li/maruchishiguworetto/nomaruchishiguworettokaraadoresuwo': 'key-management/multisig-wallet/remove-address-from-existing-multisig-wallet.md'
  'appudto/3.-shu-ming-jian-guan-li/mpc': 'key-management/mpc/README.md'
  'appudto/3.-shu-ming-jian-guan-li/mpc/mpcno': 'key-management/mpc/overview.md'
  'appudto/3.-shu-ming-jian-guan-li/mpc/mpcno-1': 'key-management/mpc/enable-mpc.md'
  'appudto/3.-shu-ming-jian-guan-li/mpc/mpcno-2': 'key-management/mpc/grant-mpc-signing-permission.md'
  'appudto/3.-shu-ming-jian-guan-li/mpc/mpcnoadoresu': 'key-management/mpc/create-mpc-address.md'
  'appudto/4n-boardnoi': 'n-board/README.md'
  'appudto/4n-boardnoi/kasutamunettowkuno': 'n-board/add-custom-network.md'
  'appudto/4n-boardnoi/nokop': 'n-board/copy-request.md'
  'appudto/4n-boardnoi/notkun': 'n-board/add-custom-token.md'
  'appudto/4n-boardnoi/sbisukarano': 'n-board/create-request-from-external-service.md'
  'appudto/5.nft-guan-lian-ji-neng': 'nft/README.md'
  'appudto/5.nft-guan-lian-ji-neng/nft-mint-fmu': 'nft/nft-mint-form.md'
  'appudto/5.nft-guan-lian-ji-neng/nft-mint-fmu-mint': 'nft/nft-mint-form-bulk-mint.md'
  'appudto/5.nft-guan-lian-ji-neng/nftmint-1txrino': 'nft/nft-bulk-mint-transaction-limit.md'
  'appudto/5.nft-guan-lian-ji-neng/nftnono': 'nft/send-nft.md'
  'appudto/6yokuaru': 'advanced-settings/README.md'
  'appudto/6yokuaru/ft-yi-kuo-song-jin-ji-neng': 'advanced-settings/bulk-ft-transfer.md'
  'appudto/6yokuaru/gasno': 'advanced-settings/edit-gas-fee.md'
  'appudto/6yokuaru/kontorakutomesoddono': 'advanced-settings/execute-contract-method.md'
  'appudto/6yokuaru/kontorakutomesoddono-1': 'advanced-settings/execute-contract-methods-in-bulk.md'
  'appudto/6yokuaru/mruadoresuno': 'advanced-settings/change-billing-email-address.md'
  'appudto/6yokuaru/nettowku': 'advanced-settings/network/README.md'
  'appudto/6yokuaru/nettowku/nettowku-arbitrum': 'advanced-settings/network/add-arbitrum-network.md'
  'appudto/6yokuaru/nettowku/nettowku-avalanche-testnet': 'advanced-settings/network/add-avalanche-testnet-network.md'
  'appudto/6yokuaru/nettowku/nettowku-bsc-binance-smart-chain': 'advanced-settings/network/add-bsc-network.md'
  'appudto/6yokuaru/nettowku/nettowku-klaytn': 'advanced-settings/network/add-klaytn-network.md'
  'appudto/6yokuaru/nettowku/nettowku-optimism': 'advanced-settings/network/add-optimism-network.md'
  'appudto/6yokuaru/purisettokontorakutono': 'advanced-settings/preset-contract-list.md'
  'appudto/6yokuaru/wallet-connect-no': 'advanced-settings/connect-wallet-connect.md'
  'appudto/7sumtofondenoi': 'mobile/README.md'
  'appudto/7sumtofondenoi/sumahoui-to': 'mobile/mobile-ui-requests.md'
  'appudto/7sumtofondenoi/sumtofonapurinitsuite': 'mobile/mobile-app.md'
  'advanced-settings/ft-yi-kuo-song-jin-ji-neng': 'advanced-settings/bulk-ft-transfer.md'
  'advanced-settings/gasno': 'advanced-settings/edit-gas-fee.md'
  'advanced-settings/kontorakutomesoddono': 'advanced-settings/execute-contract-method.md'
  'advanced-settings/kontorakutomesoddono-1': 'advanced-settings/execute-contract-methods-in-bulk.md'
  'advanced-settings/mruadoresuno': 'advanced-settings/change-billing-email-address.md'
  'advanced-settings/network/nettowku-arbitrum': 'advanced-settings/network/add-arbitrum-network.md'
  'advanced-settings/network/nettowku-avalanche-testnet': 'advanced-settings/network/add-avalanche-testnet-network.md'
  'advanced-settings/network/nettowku-bsc-binance-smart-chain': 'advanced-settings/network/add-bsc-network.md'
  'advanced-settings/network/nettowku-klaytn': 'advanced-settings/network/add-klaytn-network.md'
  'advanced-settings/network/nettowku-optimism': 'advanced-settings/network/add-optimism-network.md'
  'advanced-settings/purisettokontorakutono': 'advanced-settings/preset-contract-list.md'
  'advanced-settings/wallet-connect-no': 'advanced-settings/connect-wallet-connect.md'
  'getting-started/dong-zuo-huan-jing': 'getting-started/operating-environment.md'
  'getting-started/nettowku': 'getting-started/supported-networks.md'
  'getting-started/roguin': 'getting-started/first-login.md'
  'key-management/aws-kms/adoresunon-walletheno': 'key-management/aws-kms/add-address-to-n-wallet.md'
  'key-management/aws-kms/adoresuton-cloud-keyheno': 'key-management/aws-kms/register-address-name-in-n-cloud-key.md'
  'key-management/aws-kms/aws-kmsno-macoske': 'key-management/aws-kms/create-aws-kms-private-key-macos.md'
  'key-management/aws-kms/aws-kmsnowindowske': 'key-management/aws-kms/create-aws-kms-private-key-windows.md'
  'key-management/aws-kms/iamporishnonowosuru': 'key-management/aws-kms/create-iam-policy-for-signing.md'
  'key-management/aws-kms/iamyznonoyzwosuru': 'key-management/aws-kms/create-iam-user-for-signing.md'
  'key-management/aws-kms/n-walletnoappudto': 'key-management/aws-kms/update-n-wallet.md'
  'key-management/aws-kms/n-walletnoaws-kmsnoadoresu': 'key-management/aws-kms/register-aws-kms-address-in-n-wallet.md'
  'key-management/aws-kms/n-walletnoinsutru': 'key-management/aws-kms/install-n-wallet.md'
  'key-management/aws-kms/roguin': 'key-management/aws-kms/first-login.md'
  'key-management/ledger/adoresunon-walletheno': 'key-management/ledger/add-address-to-n-wallet.md'
  'key-management/ledger/adoresuton-cloud-keyheno': 'key-management/ledger/register-address-name-in-n-cloud-key.md'
  'key-management/ledger/n-walletnoappudto': 'key-management/ledger/update-n-wallet.md'
  'key-management/ledger/n-walletnoinsutru': 'key-management/ledger/install-n-wallet.md'
  'key-management/ledger/n-walletnoledgernoadoresu': 'key-management/ledger/register-ledger-address-in-n-wallet.md'
  'key-management/mpc/mpcno': 'key-management/mpc/overview.md'
  'key-management/mpc/mpcno-1': 'key-management/mpc/enable-mpc.md'
  'key-management/mpc/mpcno-2': 'key-management/mpc/grant-mpc-signing-permission.md'
  'key-management/mpc/mpcnoadoresu': 'key-management/mpc/create-mpc-address.md'
  'key-management/multisig-wallet/maruchishiguworettono': 'key-management/multisig-wallet/overview.md'
  'key-management/multisig-wallet/maruchishiguworettono-1': 'key-management/multisig-wallet/initial-setup.md'
  'key-management/multisig-wallet/nomaruchishiguworettoheadoresuwo': 'key-management/multisig-wallet/add-address-to-existing-multisig-wallet.md'
  'key-management/multisig-wallet/nomaruchishiguworettokaraadoresuwo': 'key-management/multisig-wallet/remove-address-from-existing-multisig-wallet.md'
  'mobile/sumahoui-to': 'mobile/mobile-ui-requests.md'
  'mobile/sumtofonapurinitsuite': 'mobile/mobile-app.md'
  'n-board/kasutamunettowkuno': 'n-board/add-custom-network.md'
  'n-board/nokop': 'n-board/copy-request.md'
  'n-board/notkun': 'n-board/add-custom-token.md'
  'n-board/sbisukarano': 'n-board/create-request-from-external-service.md'
  'nft/nft-mint-fmu': 'nft/nft-mint-form.md'
  'nft/nft-mint-fmu-mint': 'nft/nft-mint-form-bulk-mint.md'
  'nft/nftmint-1txrino': 'nft/nft-bulk-mint-transaction-limit.md'
  'nft/nftnono': 'nft/send-nft.md'
  'setup/admin/er-yao-su-ren-zheng-2fa': 'setup/admin/two-factor-authentication.md'
  'setup/admin/organization/chmuno': 'setup/admin/organization/create-team.md'
  'setup/admin/organization/henomenb': 'setup/admin/organization/add-organization-members.md'
  'setup/admin/roles/chmurruno': 'setup/admin/roles/team-roles.md'
  'setup/admin/roles/rruno': 'setup/admin/roles/organization-roles.md'
  'setup/admin/team/chmuhenoadoresu': 'setup/admin/team/register-team-addresses.md'
  'setup/admin/team/chmuhenomenb': 'setup/admin/team/add-team-members.md'
  'setup/admin/team/chmumenbno': 'setup/admin/team/edit-delete-team-members.md'
  'setup/admin/workflow/purosesuni-wosuru': 'setup/admin/workflow/set-process-conditions.md'
  'setup/admin/workflow/wkufurnopurosesu': 'setup/admin/workflow/configure-workflow-process.md'
