structure:
  readme: README.md
  summary: SUMMARY.md

redirects:
  'appudto/1hajimeni/dong-zuo-huan-jing': 'getting-started/dong-zuo-huan-jing.md'
  'appudto/1hajimeni/nettowku': 'getting-started/nettowku.md'
  'appudto/1hajimeni/roguin': 'getting-started/roguin.md'
  'appudto/2matome': 'setup/README.md'
  'appudto/2matome/ke': 'setup/admin/README.md'
  'appudto/2matome/ke/chmurru': 'setup/admin/organization-team-roles/README.md'
  'appudto/2matome/ke/chmurru/chmu': 'setup/admin/team/README.md'
  'appudto/2matome/ke/chmurru/chmu/chmuhenoadoresu': 'setup/admin/team/chmuhenoadoresu.md'
  'appudto/2matome/ke/chmurru/chmu/chmuhenomenb': 'setup/admin/team/chmuhenomenb.md'
  'appudto/2matome/ke/chmurru/chmu/chmumenbno': 'setup/admin/team/chmumenbno.md'
  'appudto/2matome/ke/chmurru/rru': 'setup/admin/roles/README.md'
  'appudto/2matome/ke/chmurru/rru/chmurruno': 'setup/admin/roles/chmurruno.md'
  'appudto/2matome/ke/chmurru/rru/rruno': 'setup/admin/roles/rruno.md'
  'appudto/2matome/ke/chmurru/zu-zhi': 'setup/admin/organization/README.md'
  'appudto/2matome/ke/chmurru/zu-zhi/chmuno': 'setup/admin/organization/chmuno.md'
  'appudto/2matome/ke/chmurru/zu-zhi/henomenb': 'setup/admin/organization/henomenb.md'
  'appudto/2matome/ke/er-yao-su-ren-zheng-2fa': 'setup/admin/er-yao-su-ren-zheng-2fa.md'
  'appudto/2matome/ke/wkufur': 'setup/admin/workflow/README.md'
  'appudto/2matome/ke/wkufur/purosesuni-wosuru': 'setup/admin/workflow/purosesuni-wosuru.md'
  'appudto/2matome/ke/wkufur/wkufurnopurosesu': 'setup/admin/workflow/wkufurnopurosesu.md'
  'appudto/3.-shu-ming-jian-guan-li': 'key-management/README.md'
  'appudto/3.-shu-ming-jian-guan-li/aws-kms': 'key-management/aws-kms/README.md'
  'appudto/3.-shu-ming-jian-guan-li/aws-kms/adoresunon-walletheno': 'key-management/aws-kms/adoresunon-walletheno.md'
  'appudto/3.-shu-ming-jian-guan-li/aws-kms/adoresuton-cloud-keyheno': 'key-management/aws-kms/adoresuton-cloud-keyheno.md'
  'appudto/3.-shu-ming-jian-guan-li/aws-kms/aws-kmsno-macoske': 'key-management/aws-kms/aws-kmsno-macoske.md'
  'appudto/3.-shu-ming-jian-guan-li/aws-kms/aws-kmsnowindowske': 'key-management/aws-kms/aws-kmsnowindowske.md'
  'appudto/3.-shu-ming-jian-guan-li/aws-kms/iamporishnonowosuru': 'key-management/aws-kms/iamporishnonowosuru.md'
  'appudto/3.-shu-ming-jian-guan-li/aws-kms/iamyznonoyzwosuru': 'key-management/aws-kms/iamyznonoyzwosuru.md'
  'appudto/3.-shu-ming-jian-guan-li/aws-kms/n-walletnoappudto': 'key-management/aws-kms/n-walletnoappudto.md'
  'appudto/3.-shu-ming-jian-guan-li/aws-kms/n-walletnoaws-kmsnoadoresu': 'key-management/aws-kms/n-walletnoaws-kmsnoadoresu.md'
  'appudto/3.-shu-ming-jian-guan-li/aws-kms/n-walletnoinsutru': 'key-management/aws-kms/n-walletnoinsutru.md'
  'appudto/3.-shu-ming-jian-guan-li/aws-kms/roguin': 'key-management/aws-kms/roguin.md'
  'appudto/3.-shu-ming-jian-guan-li/ledger': 'key-management/ledger/README.md'
  'appudto/3.-shu-ming-jian-guan-li/ledger/adoresunon-walletheno': 'key-management/ledger/adoresunon-walletheno.md'
  'appudto/3.-shu-ming-jian-guan-li/ledger/adoresuton-cloud-keyheno': 'key-management/ledger/adoresuton-cloud-keyheno.md'
  'appudto/3.-shu-ming-jian-guan-li/ledger/n-walletnoappudto': 'key-management/ledger/n-walletnoappudto.md'
  'appudto/3.-shu-ming-jian-guan-li/ledger/n-walletnoinsutru': 'key-management/ledger/n-walletnoinsutru.md'
  'appudto/3.-shu-ming-jian-guan-li/ledger/n-walletnoledgernoadoresu': 'key-management/ledger/n-walletnoledgernoadoresu.md'
  'appudto/3.-shu-ming-jian-guan-li/maruchishiguworetto': 'key-management/multisig-wallet/README.md'
  'appudto/3.-shu-ming-jian-guan-li/maruchishiguworetto/maruchishiguworettono': 'key-management/multisig-wallet/maruchishiguworettono.md'
  'appudto/3.-shu-ming-jian-guan-li/maruchishiguworetto/maruchishiguworettono-1': 'key-management/multisig-wallet/maruchishiguworettono-1.md'
  'appudto/3.-shu-ming-jian-guan-li/maruchishiguworetto/nomaruchishiguworettoheadoresuwo': 'key-management/multisig-wallet/nomaruchishiguworettoheadoresuwo.md'
  'appudto/3.-shu-ming-jian-guan-li/maruchishiguworetto/nomaruchishiguworettokaraadoresuwo': 'key-management/multisig-wallet/nomaruchishiguworettokaraadoresuwo.md'
  'appudto/3.-shu-ming-jian-guan-li/mpc': 'key-management/mpc/README.md'
  'appudto/3.-shu-ming-jian-guan-li/mpc/mpcno': 'key-management/mpc/mpcno.md'
  'appudto/3.-shu-ming-jian-guan-li/mpc/mpcno-1': 'key-management/mpc/mpcno-1.md'
  'appudto/3.-shu-ming-jian-guan-li/mpc/mpcno-2': 'key-management/mpc/mpcno-2.md'
  'appudto/3.-shu-ming-jian-guan-li/mpc/mpcnoadoresu': 'key-management/mpc/mpcnoadoresu.md'
  'appudto/4n-boardnoi': 'n-board/README.md'
  'appudto/4n-boardnoi/kasutamunettowkuno': 'n-board/kasutamunettowkuno.md'
  'appudto/4n-boardnoi/nokop': 'n-board/nokop.md'
  'appudto/4n-boardnoi/notkun': 'n-board/notkun.md'
  'appudto/4n-boardnoi/sbisukarano': 'n-board/sbisukarano.md'
  'appudto/5.nft-guan-lian-ji-neng': 'nft/README.md'
  'appudto/5.nft-guan-lian-ji-neng/nft-mint-fmu': 'nft/nft-mint-fmu.md'
  'appudto/5.nft-guan-lian-ji-neng/nft-mint-fmu-mint': 'nft/nft-mint-fmu-mint.md'
  'appudto/5.nft-guan-lian-ji-neng/nftmint-1txrino': 'nft/nftmint-1txrino.md'
  'appudto/5.nft-guan-lian-ji-neng/nftnono': 'nft/nftnono.md'
  'appudto/6yokuaru': 'advanced-settings/README.md'
  'appudto/6yokuaru/ft-yi-kuo-song-jin-ji-neng': 'advanced-settings/ft-yi-kuo-song-jin-ji-neng.md'
  'appudto/6yokuaru/gasno': 'advanced-settings/gasno.md'
  'appudto/6yokuaru/kontorakutomesoddono': 'advanced-settings/kontorakutomesoddono.md'
  'appudto/6yokuaru/kontorakutomesoddono-1': 'advanced-settings/kontorakutomesoddono-1.md'
  'appudto/6yokuaru/mruadoresuno': 'advanced-settings/mruadoresuno.md'
  'appudto/6yokuaru/nettowku': 'advanced-settings/network/README.md'
  'appudto/6yokuaru/nettowku/nettowku-arbitrum': 'advanced-settings/network/nettowku-arbitrum.md'
  'appudto/6yokuaru/nettowku/nettowku-avalanche-testnet': 'advanced-settings/network/nettowku-avalanche-testnet.md'
  'appudto/6yokuaru/nettowku/nettowku-bsc-binance-smart-chain': 'advanced-settings/network/nettowku-bsc-binance-smart-chain.md'
  'appudto/6yokuaru/nettowku/nettowku-klaytn': 'advanced-settings/network/nettowku-klaytn.md'
  'appudto/6yokuaru/nettowku/nettowku-optimism': 'advanced-settings/network/nettowku-optimism.md'
  'appudto/6yokuaru/purisettokontorakutono': 'advanced-settings/purisettokontorakutono.md'
  'appudto/6yokuaru/wallet-connect-no': 'advanced-settings/wallet-connect-no.md'
  'appudto/7sumtofondenoi': 'mobile/README.md'
  'appudto/7sumtofondenoi/sumahoui-to': 'mobile/sumahoui-to.md'
  'appudto/7sumtofondenoi/sumtofonapurinitsuite': 'mobile/sumtofonapurinitsuite.md'
